import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tyab EL Assil",
  description: "Generated by TyabSeha team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="description" content="Découvrez Tyab El Assil, une plateforme dédiée à la cuisine marocaine faite maison par des femmes talentueuses." />
        <meta name="robots" content="index, follow" />
        <meta name="keywords" content="Tyab El Assil, cuisine marocaine, plats faits maison, femmes cuisinières, repas marocains" />
        <link rel="canonical" href="https://ma-nine-sable.vercel.app" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
